repos:
  - repo: local
    hooks:
      - id: conda-forge-only
        name: conda-forge-only
        entry: python -m conda_forge_only.check_channels
        language: system
        files: \.(yml|yaml)$